# http://localhost:8080/test/testRequestBody
GET http://localhost:8080/test/testReqBody
Content-Type: application/json

{
  "id": 123,
  "message": "sdfs"
}

###
GET http://localhost:8080/test/testRespBody
Content-Type: application/json

###
GET http://localhost:8080/test/testRespEntity
Content-Type: application/json

###
GET http://localhost:8080/todo/test
Content-Type: application/json

###
GET http://localhost:8080/todo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0MDI4OTE4MjdmODJkYTIyMDE3ZjgyZGIzNTZlMDAwMCIsImlzcyI6InJ0IiwiaWF0IjoxNjQ3MTY4MDY4LCJleHAiOjE2NDcyNTQ0Njh9.1Hq2sTV0qSho4_VNuG_Uxr6pK8cyvP1GME5DKyKdOacuWLRveitkEreniUfQBIdWNSMU_l9Lps7Mb7Bfd1_LfA
